server:
  port: 8080

spring:
  profiles:
    active: default  # caffeine или redis
  application:
    name: AdFeedApplication
  boot:
    admin:
      client:
        url: http://localhost:8081
        username: admin
        password: admin
        instance:
          name: AdFeed Application
          service-url: http://localhost:8080
          management-url: http://localhost:8080/actuator
          health-url: http://localhost:8080/actuator/health
          metadata:
            user.name: admin
            user.password: admin
        enabled: false
        period: 10000
        connect-timeout: 5000
        read-timeout: 5000
        register-once: true
        auto-registration: true

# Настройки Feign клиентов
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
      backoffice-client:
        url: http://localhost:8082
        connectTimeout: 3000
        readTimeout: 5000